git:
    submodules: true

matrix:
    include:
        - name: "Build"
          language: cpp
          compiler: gcc
          os: linux
          language: c++
          before_script:
            - sudo apt-get install gcc-arm-none-eabi
          script:
            - "cd arm_controller/ && make"


notifications:
    email: false
