/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/isthatme/Documents/Clubs/SPEAR/dsdl/spear/drive/20001.DriveStatus.uavcan
 */

#ifndef __SPEAR_DRIVE_DRIVESTATUS
#define __SPEAR_DRIVE_DRIVESTATUS

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
#
# Status message for drive motors
#

# ID of wheel
uint3 wheel

# Speed wheel is *currently* turning at (signed mm/s)
int13 speed
******************************************************************************/

/********************* DSDL signature source definition ***********************
spear.drive.DriveStatus
saturated uint3 wheel
saturated int13 speed
******************************************************************************/

#define SPEAR_DRIVE_DRIVESTATUS_ID                         20001
#define SPEAR_DRIVE_DRIVESTATUS_NAME                       "spear.drive.DriveStatus"
#define SPEAR_DRIVE_DRIVESTATUS_SIGNATURE                  (0xCB5107201E8C4FC7ULL)

#define SPEAR_DRIVE_DRIVESTATUS_MAX_SIZE                   ((16 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    uint8_t    wheel;                         // bit len 3
    int16_t    speed;                         // bit len 13

} spear_drive_DriveStatus;

extern
uint32_t spear_drive_DriveStatus_encode(spear_drive_DriveStatus* source, void* msg_buf);

extern
int32_t spear_drive_DriveStatus_decode(const CanardRxTransfer* transfer, uint16_t payload_len, spear_drive_DriveStatus* dest, uint8_t** dyn_arr_buf);

extern
uint32_t spear_drive_DriveStatus_encode_internal(spear_drive_DriveStatus* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t spear_drive_DriveStatus_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, spear_drive_DriveStatus* dest, uint8_t** dyn_arr_buf, int32_t offset);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __SPEAR_DRIVE_DRIVESTATUS