/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/isthatme/Documents/Clubs/SPEAR/dsdl/spear/drive/20000.DriveCommand.uavcan
 */
#include "spear/drive/DriveCommand.h"
#include "canard.h"

#ifndef CANARD_INTERNAL_SATURATE
#define CANARD_INTERNAL_SATURATE(x, max) ( ((x) > max) ? max : ( (-(x) > max) ? (-max) : (x) ) );
#endif

#define CANARD_INTERNAL_ENABLE_TAO  ((uint8_t) 1)
#define CANARD_INTERNAL_DISABLE_TAO ((uint8_t) 0)

/**
  * @brief spear_drive_DriveCommand_encode_internal
  * @param source : pointer to source data struct
  * @param msg_buf: pointer to msg storage
  * @param offset: bit offset to msg storage
  * @param root_item: for detecting if TAO should be used
  * @retval returns offset
  */
uint32_t spear_drive_DriveCommand_encode_internal(spear_drive_DriveCommand* source, void* msg_buf, uint32_t offset, uint8_t root_item)
{
    source->joint = CANARD_INTERNAL_SATURATE(source->joint, 15)
    canardEncodeScalar(msg_buf, offset, 4, (void*)&source->joint); // 15
    offset += 4;

    source->angle = CANARD_INTERNAL_SATURATE(source->angle, 4095)
    canardEncodeScalar(msg_buf, offset, 12, (void*)&source->angle); // 4095
    offset += 12;

    return offset;
}

/**
  * @brief spear_drive_DriveCommand_encode
  * @param source : Pointer to source data struct
  * @param msg_buf: Pointer to msg storage
  * @retval returns message length as bytes
  */
uint32_t spear_drive_DriveCommand_encode(spear_drive_DriveCommand* source, void* msg_buf)
{
    uint32_t offset = 0;

    offset = spear_drive_DriveCommand_encode_internal(source, msg_buf, offset, 1);

    return (offset + 7 ) / 8;
}

/**
  * @brief spear_drive_DriveCommand_decode_internal
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     spear_drive_DriveCommand dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @param offset: Call with 0, bit offset to msg storage
  * @param tao: is tail array optimization used
  * @retval offset or ERROR value if < 0
  */
int32_t spear_drive_DriveCommand_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, spear_drive_DriveCommand* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao)
{
    int32_t ret = 0;

    ret = canardDecodeScalar(transfer, offset, 4, false, (void*)&dest->joint);
    if (ret != 4)
    {
        goto spear_drive_DriveCommand_error_exit;
    }
    offset += 4;

    ret = canardDecodeScalar(transfer, offset, 12, false, (void*)&dest->angle);
    if (ret != 12)
    {
        goto spear_drive_DriveCommand_error_exit;
    }
    offset += 12;
    return offset;

spear_drive_DriveCommand_error_exit:
    if (ret < 0)
    {
        return ret;
    }
    else
    {
        return -CANARD_ERROR_INTERNAL;
    }
}

/**
  * @brief spear_drive_DriveCommand_decode
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     spear_drive_DriveCommand dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @retval offset or ERROR value if < 0
  */
int32_t spear_drive_DriveCommand_decode(const CanardRxTransfer* transfer, uint16_t payload_len, spear_drive_DriveCommand* dest, uint8_t** dyn_arr_buf)
{
    const int32_t offset = 0;
    int32_t ret = 0;

    /* Backward compatibility support for removing TAO
     *  - first try to decode with TAO DISABLED
     *  - if it fails fall back to TAO ENABLED
     */
    uint8_t tao = CANARD_INTERNAL_DISABLE_TAO;

    while (1)
    {
        // Clear the destination struct
        for (uint32_t c = 0; c < sizeof(spear_drive_DriveCommand); c++)
        {
            ((uint8_t*)dest)[c] = 0x00;
        }

        ret = spear_drive_DriveCommand_decode_internal(transfer, payload_len, dest, dyn_arr_buf, offset, tao);

        if (ret >= 0)
        {
            break;
        }

        if (tao == CANARD_INTERNAL_ENABLE_TAO)
        {
            break;
        }
        tao = CANARD_INTERNAL_ENABLE_TAO;
    }

    return ret;
}
