/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/isthatme/Documents/Clubs/SPEAR/dsdl/spear/drive/20000.DriveCommand.uavcan
 */

#ifndef __SPEAR_DRIVE_DRIVECOMMAND
#define __SPEAR_DRIVE_DRIVECOMMAND

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
#
# Command to move arm joints
#

# ID of joint
uint4 joint

# Angle to move to (unsigned tenths of a degree)
uint12 angle
******************************************************************************/

/********************* DSDL signature source definition ***********************
spear.drive.DriveCommand
saturated uint4 joint
saturated uint12 angle
******************************************************************************/

#define SPEAR_DRIVE_DRIVECOMMAND_ID                        20000
#define SPEAR_DRIVE_DRIVECOMMAND_NAME                      "spear.drive.DriveCommand"
#define SPEAR_DRIVE_DRIVECOMMAND_SIGNATURE                 (0x700D36E8F04E585FULL)

#define SPEAR_DRIVE_DRIVECOMMAND_MAX_SIZE                  ((16 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    uint8_t    joint;                         // bit len 4
    uint16_t   angle;                         // bit len 12

} spear_drive_DriveCommand;

extern
uint32_t spear_drive_DriveCommand_encode(spear_drive_DriveCommand* source, void* msg_buf);

extern
int32_t spear_drive_DriveCommand_decode(const CanardRxTransfer* transfer, uint16_t payload_len, spear_drive_DriveCommand* dest, uint8_t** dyn_arr_buf);

extern
uint32_t spear_drive_DriveCommand_encode_internal(spear_drive_DriveCommand* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t spear_drive_DriveCommand_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, spear_drive_DriveCommand* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __SPEAR_DRIVE_DRIVECOMMAND