/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/isthatme/Documents/Clubs/SPEAR/dsdl/uavcan_dsdl/uavcan/equipment/air_data/1026.Sideslip.uavcan
 */

#ifndef __UAVCAN_EQUIPMENT_AIR_DATA_SIDESLIP
#define __UAVCAN_EQUIPMENT_AIR_DATA_SIDESLIP

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
#
# Body sideslip in radians.
#

float16 sideslip_angle          # Radians
float16 sideslip_angle_variance # Radians^2
******************************************************************************/

/********************* DSDL signature source definition ***********************
uavcan.equipment.air_data.Sideslip
saturated float16 sideslip_angle
saturated float16 sideslip_angle_variance
******************************************************************************/

#define UAVCAN_EQUIPMENT_AIR_DATA_SIDESLIP_ID              1026
#define UAVCAN_EQUIPMENT_AIR_DATA_SIDESLIP_NAME            "uavcan.equipment.air_data.Sideslip"
#define UAVCAN_EQUIPMENT_AIR_DATA_SIDESLIP_SIGNATURE       (0x7B48E55FCFF42A57ULL)

#define UAVCAN_EQUIPMENT_AIR_DATA_SIDESLIP_MAX_SIZE        ((32 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    float      sideslip_angle;                // float16 Saturate
    float      sideslip_angle_variance;       // float16 Saturate

} uavcan_equipment_air_data_Sideslip;

extern
uint32_t uavcan_equipment_air_data_Sideslip_encode(uavcan_equipment_air_data_Sideslip* source, void* msg_buf);

extern
int32_t uavcan_equipment_air_data_Sideslip_decode(const CanardRxTransfer* transfer, uint16_t payload_len, uavcan_equipment_air_data_Sideslip* dest, uint8_t** dyn_arr_buf);

extern
uint32_t uavcan_equipment_air_data_Sideslip_encode_internal(uavcan_equipment_air_data_Sideslip* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t uavcan_equipment_air_data_Sideslip_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, uavcan_equipment_air_data_Sideslip* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __UAVCAN_EQUIPMENT_AIR_DATA_SIDESLIP