/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/isthatme/Documents/Clubs/SPEAR/dsdl/spear/arm/20100.JointCommand.uavcan
 */
#include "spear/arm/JointCommand.h"
#include "canard.h"

#ifndef CANARD_INTERNAL_SATURATE
#define CANARD_INTERNAL_SATURATE(x, max) ( ((x) > max) ? max : ( (-(x) > max) ? (-max) : (x) ) );
#endif

#ifndef CANARD_INTERNAL_SATURATE_UNSIGNED
#define CANARD_INTERNAL_SATURATE_UNSIGNED(x, max) ( ((x) > max) ? max : (x) );
#endif

#if defined(__GNUC__)
# define CANARD_MAYBE_UNUSED(x) x __attribute__((unused))
#else
# define CANARD_MAYBE_UNUSED(x) x
#endif

/**
  * @brief spear_arm_JointCommand_encode_internal
  * @param source : pointer to source data struct
  * @param msg_buf: pointer to msg storage
  * @param offset: bit offset to msg storage
  * @param root_item: for detecting if TAO should be used
  * @retval returns offset
  */
uint32_t spear_arm_JointCommand_encode_internal(spear_arm_JointCommand* source,
  void* msg_buf,
  uint32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(root_item))
{
    source->joint = CANARD_INTERNAL_SATURATE_UNSIGNED(source->joint, 15)
    canardEncodeScalar(msg_buf, offset, 4, (void*)&source->joint); // 15
    offset += 4;

    source->angle = CANARD_INTERNAL_SATURATE_UNSIGNED(source->angle, 4095)
    canardEncodeScalar(msg_buf, offset, 12, (void*)&source->angle); // 4095
    offset += 12;

    return offset;
}

/**
  * @brief spear_arm_JointCommand_encode
  * @param source : Pointer to source data struct
  * @param msg_buf: Pointer to msg storage
  * @retval returns message length as bytes
  */
uint32_t spear_arm_JointCommand_encode(spear_arm_JointCommand* source, void* msg_buf)
{
    uint32_t offset = 0;

    offset = spear_arm_JointCommand_encode_internal(source, msg_buf, offset, 1);

    return (offset + 7 ) / 8;
}

/**
  * @brief spear_arm_JointCommand_decode_internal
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     spear_arm_JointCommand dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @param offset: Call with 0, bit offset to msg storage
  * @retval offset or ERROR value if < 0
  */
int32_t spear_arm_JointCommand_decode_internal(
  const CanardRxTransfer* transfer,
  uint16_t CANARD_MAYBE_UNUSED(payload_len),
  spear_arm_JointCommand* dest,
  uint8_t** CANARD_MAYBE_UNUSED(dyn_arr_buf),
  int32_t offset)
{
    int32_t ret = 0;

    ret = canardDecodeScalar(transfer, offset, 4, false, (void*)&dest->joint);
    if (ret != 4)
    {
        goto spear_arm_JointCommand_error_exit;
    }
    offset += 4;

    ret = canardDecodeScalar(transfer, offset, 12, false, (void*)&dest->angle);
    if (ret != 12)
    {
        goto spear_arm_JointCommand_error_exit;
    }
    offset += 12;
    return offset;

spear_arm_JointCommand_error_exit:
    if (ret < 0)
    {
        return ret;
    }
    else
    {
        return -CANARD_ERROR_INTERNAL;
    }
}

/**
  * @brief spear_arm_JointCommand_decode
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     spear_arm_JointCommand dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @retval offset or ERROR value if < 0
  */
int32_t spear_arm_JointCommand_decode(const CanardRxTransfer* transfer,
  uint16_t payload_len,
  spear_arm_JointCommand* dest,
  uint8_t** dyn_arr_buf)
{
    const int32_t offset = 0;
    int32_t ret = 0;

    // Clear the destination struct
    for (uint32_t c = 0; c < sizeof(spear_arm_JointCommand); c++)
    {
        ((uint8_t*)dest)[c] = 0x00;
    }

    ret = spear_arm_JointCommand_decode_internal(transfer, payload_len, dest, dyn_arr_buf, offset);

    return ret;
}
