/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/isthatme/Documents/Clubs/SPEAR/dsdl/spear/arm/20101.JointStatus.uavcan
 */

#ifndef __SPEAR_ARM_JOINTSTATUS
#define __SPEAR_ARM_JOINTSTATUS

#include <stdint.h>
#include "canard.h"

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
#
# Status message for location of arm joint
#

# ID of joint
uint4 joint

# Angle joint is *currently* at (unsigned tenths of a degree)
uint12 angle
******************************************************************************/

/********************* DSDL signature source definition ***********************
spear.arm.JointStatus
saturated uint4 joint
saturated uint12 angle
******************************************************************************/

#define SPEAR_ARM_JOINTSTATUS_ID                           20101
#define SPEAR_ARM_JOINTSTATUS_NAME                         "spear.arm.JointStatus"
#define SPEAR_ARM_JOINTSTATUS_SIGNATURE                    (0x19899CB312099F3CULL)

#define SPEAR_ARM_JOINTSTATUS_MAX_SIZE                     ((16 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    uint8_t    joint;                         // bit len 4
    uint16_t   angle;                         // bit len 12

} spear_arm_JointStatus;

extern
uint32_t spear_arm_JointStatus_encode(spear_arm_JointStatus* source, void* msg_buf);

extern
int32_t spear_arm_JointStatus_decode(const CanardRxTransfer* transfer, uint16_t payload_len, spear_arm_JointStatus* dest, uint8_t** dyn_arr_buf);

extern
uint32_t spear_arm_JointStatus_encode_internal(spear_arm_JointStatus* source, void* msg_buf, uint32_t offset, uint8_t root_item);

extern
int32_t spear_arm_JointStatus_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, spear_arm_JointStatus* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __SPEAR_ARM_JOINTSTATUS